# Build stage
FROM node:16-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install

# Production stage
FROM node:16-alpine
WORKDIR /app
COPY --from=build /app .
COPY src ./src 
COPY prisma ./prisma 
RUN npx prisma generate 
EXPOSE 5000
CMD ["npm", "run", "dev"]